BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"

TRAIN:
  BATCH_SIZE: 180
  EPOCHS: 5
  LR: 1e-3
  MODEL_FILE_NAME: BP4D_BP4D_bigsmall_fold3
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 25
    DATASET: BP4DPlusBigSmall
    DO_PREPROCESS: False              # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:  "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/BP4DPlus/RawData" 
    CACHED_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/rppg_toolbox/PreprocessedData"  # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "BigSmall_BP4DPlus_Big144_Small9_ChunkLen3_AUSubset_rPPGToolbox"
    FOLD:
      FOLD_NAME: 'Fold3_Train'
      FOLD_PATH: './dataset/BP4D_BigSmall_Subject_Splits/Split3_Train_Subjects.csv'
    PREPROCESS:
      USE_PSUEDO_PPG_LABEL: True
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 3
      CROP_FACE:
        DO_CROP_FACE: False
        USE_LARGE_FACE_BOX: False
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 180
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      BIGSMALL:
        BIG_DATA_TYPE: ['Standardized']
        SMALL_DATA_TYPE: ['DiffNormalized']
        RESIZE:
          BIG_H: 144
          BIG_W: 144
          SMALL_H: 9
          SMALL_W: 9

VALID:
  DATA:
    FS: 25
    DATASET: BP4DPlusBigSmall
    DO_PREPROCESS: False              # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:  "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/BP4DPlus/RawData" 
    CACHED_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/rppg_toolbox/PreprocessedData"  # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "BigSmall_BP4DPlus_Big144_Small9_ChunkLen3_AUSubset_rPPGToolbox"
    FOLD:
      FOLD_NAME: 'Fold3_Test'
      FOLD_PATH: './dataset/BP4D_BigSmall_Subject_Splits/Split3_Test_Subjects.csv'
    PREPROCESS:
      USE_PSUEDO_PPG_LABEL: True
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 3
      CROP_FACE:
        DO_CROP_FACE: False
        USE_LARGE_FACE_BOX: False
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 180
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      BIGSMALL:
        BIG_DATA_TYPE: ['Standardized']
        SMALL_DATA_TYPE: ['DiffNormalized']
        RESIZE:
          BIG_H: 144
          BIG_W: 144
          SMALL_H: 9
          SMALL_W: 9

TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA', 'AU_METRICS']
  USE_LAST_EPOCH: True                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 25
    DATASET: BP4DPlusBigSmall
    DO_PREPROCESS: False              # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:  "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/BP4DPlus/RawData" 
    CACHED_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/rppg_toolbox/PreprocessedData"  # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "BigSmall_BP4DPlus_Big144_Small9_ChunkLen3_AUSubset_rPPGToolbox"
    FOLD:
      FOLD_NAME: 'Fold3_Test'
      FOLD_PATH: './dataset/BP4D_BigSmall_Subject_Splits/Split3_Test_Subjects.csv'
    PREPROCESS:
      USE_PSUEDO_PPG_LABEL: True
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 3
      CROP_FACE:
        DO_CROP_FACE: False
        USE_LARGE_FACE_BOX: False
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 180
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      BIGSMALL:
        BIG_DATA_TYPE: ['Standardized']
        SMALL_DATA_TYPE: ['DiffNormalized']
        RESIZE:
          BIG_H: 144
          BIG_W: 144
          SMALL_H: 9
          SMALL_W: 9

DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 2

LOG:
  PATH: runs/exp

MODEL:
  NAME: BigSmall
  BIGSMALL:
    FRAME_DEPTH: 3

INFERENCE:
  BATCH_SIZE: 180
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  MODEL_PATH: ""
