BASE: ['']
DATA:
  FS: 30
  DATASET: PURE
  DO_PREPROCESS: True # This can be False after first time preprocessing.
  DATA_FORMAT: NDCHW
  TRAIN_DATA_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/PURE/RawData/" # To be updated
  # Note: This config does not need a validation data
  EXP_DATA_NAME: "PURE_72x72_Normalized_Standardized_Pilot" # To be updated
  PREPROCESS :
    DATA_TYPE: ['Normalized','Standardized']
    LABEL_TYPE : Normalized
    CLIP_LENGTH: 180
    CROP_FACE: True
    H: 72
    W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 4 # To be updated
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 20
TRAIN:
  BATCH_SIZE: 8
  EPOCHS: 10
  LR: 0.0001
  MODEL_FILE_NAME: tscan_pure_10epoch_geforce2080ti_pilot # To be updated