BASE: ['']
DATA:
  FS: 30
  DATASET: PURE
  DO_PREPROCESS: False
  DATA_FORMAT: NDCHW
  TEST_DATA_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/PURE/RawData"
  EXP_DATA_NAME: "PURE_72x72/test"
  PREPROCESS :
    DATA_TYPE: ['Normalized','Standardized']
    LABEL_TYPE : Normalized
    CLIP_LENGTH: 180
    CROP_FACE: True
    H: 72
    W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 2
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: DeepPhys
INFERENCE:
  BATCH_SIZE: 1
  MODEL_PATH: './PreTrainedModels/SYNTHETICS_Tscan_SizeW72_SizeH72_ClipLength180_DataTypeNormalized_Standardized_LabelTypeNormalized/deepphys_synthetics.pth'
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
