BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 10
  LR: 1e-3
  MODEL_FILE_NAME: SCAMPS_SCAMPS_UBFC_deepphys
  DATA:
    FS: 30
    DATASET: SCAMPS
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "/data2/rppg_datasets/scamps/RawData/Train"    # Raw dataset path, need to be updated
    CACHED_PATH: "/data2/rppg_datasets/PreprocessedData/"       # Processed dataset save path, need to be updated
    FILE_LIST_PATH: "/data2/rppg_datasets/DataFileLists/"       # Path to store file lists, needs to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['Normalized','Standardized']
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
VALID:
  DATA:
    FS: 30
    DATASET: SCAMPS
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "/data2/rppg_datasets/scamps/RawData/Val"   # Raw dataset path, need to be updated
    CACHED_PATH: "/data2/rppg_datasets/PreprocessedData/"    # Processed dataset save path, need to be updated
    FILE_LIST_PATH: "/data2/rppg_datasets/DataFileLists/"    # Path to store file lists, needs to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Normalized','Standardized' ]
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "/data1/toolbox_data/UBFC/RawData"          # Raw dataset path, need to be updated
    CACHED_PATH: "/data2/rppg_datasets/PreprocessedData/"    # Processed dataset save path, need to be updated
    FILE_LIST_PATH: "/data2/rppg_datasets/DataFileLists/"    # Path to store file lists, needs to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Normalized','Standardized' ]
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: DeepPhys
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: FFT        # "FFT" or "peak detection"
  MODEL_PATH:   ""
                  
