BASE: ['']
TOOLBOX_MODE: "train_and_test" # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 10
  LR: 1e-3
  MODEL_FILE_NAME: UBFC_UBFC_PURE_physnet
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: False            # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH:   "/data1/toolbox_data/UBFC/RawData"       # need to be updated
    CACHED_PATH: "/data2/rppg_datasets/PreprocessedData/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.8
    PREPROCESS :
      DATA_TYPE: [ 'Normalized' ]
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 128
      W: 128
VALID:
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: False                # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/data1/toolbox_data/UBFC/RawData"   # need to be updated
    CACHED_PATH: "/data2/rppg_datasets/PreprocessedData/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Normalized' ]
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 128
      W: 128
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/data1/toolbox_data/PURE/RawData"     # need to be updated
    CACHED_PATH: "/data2/rppg_datasets/PreprocessedData/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Normalized' ]
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 128
      W: 128
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: Physnet
  PHYSNET:
    FRAME_NUM: 128
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: FFT        # "FFT" or "peak detection"
  MODEL_PATH: ""