BASE: ['']
DATA:
  CACHED_PATH: preprocess
  DATASET: UBFC
  DO_PREPROCESS: False
  DATA_FORMAT: NDCHW
  PREPROCESS :
    DATA_TYPE: ['Standardized','Normalized' ]
    LABEL_TYPE : Normalized
    CLIP_LENGTH: 180
    CROP_FACE: True
    H: 36
    W: 36
DEVICE: cuda:0
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  MODEL_DIR: store_model
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 10
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 30
  LR: 0.0001
  MODEL_FILE_NAME: tscan.pth
  