BASE: ['']
TOOLBOX_MODE: "unsupervised_method"      # "train_and_test"  or "only_test" or "unsupervised_method"
UNSUPERVISED:
  METHOD: ["ICA", "POS", "CHROM", "GREEN", "LGI", "PBV"]
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  DATA:
    INFO:
      LIGHT: [1, 2, 3]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
      MOTION: [1] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
      EXERCISE: [2] # 1 - True, 2 - False
      SKIN_COLOR: [3] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
      GENDER: [1, 2]  # 1 - Male, 2 - Female
      GLASSER: [1, 2] # 1 - True, 2 - False
      HAIR_COVER: [1, 2] # 1 - True, 2 - False
      MAKEUP: [1, 2] # 1 - True, 2 - False
    FS: 30
    DATASET: MMPD
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDHWC
    DATA_PATH:   "/data/rPPG_dataset/mat_dataset"          # Raw dataset path, need to be updated
    CACHED_PATH: "/data/rPPG_dataset/processed_dataset"      # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['Raw']
      LABEL_TYPE: Raw
      DO_CHUNK: False
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
INFERENCE:
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
