BASE: ['']
TOOLBOX_MODE: "unsupervised_method"      # "train_and_test"  or "only_test" or "unsupervised_method"
UNSUPERVISED:
  METHOD: ["ICA", "POS", "CHROM", "GREEN", "LGI", "PBV"]
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  DATA:
    INFO:
      LIGHT: [1, 2, 3]  # 'LED-low','LED-high','Incandescent','Nature'
      MOTION: [1] # 'Stationary', 'Rotation', 'Talking', 'Walking'
      EXERCISE: [2] # True, False
      SKIN_COLOR: [3] # 3, 4, 5, 6
      GENDER: [1, 2]  # 'male','female'
      GLASSER: [1, 2] # True, False
      HAIR_COVER: [1, 2] # True, False
      MAKEUP: [1, 2] # True, False
    FS: 30
    DATASET: MMPD
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDHWC
    DATA_PATH:   "/data/rPPG_dataset/mat_dataset"          # Raw dataset path, need to be updated
    CACHED_PATH: "/data/rPPG_dataset/processed_dataset"      # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['Raw']
      LABEL_TYPE: Raw
      DO_CHUNK: False
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
INFERENCE:
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
                  
